sudo: false
languag: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - iojs
before_install:
  - npm i g npm@latest
before_script:
  - npm prune
script:
  - npm run test
after_success:
  - npm run semantic-release

