sudo: false
languag: node_js
notifications:
  email: false
node_js:
  - iojs
before_install:
  - npm i g npm@latest
before_script:
  - npm prune
script:
  - npm run test
  - npm run check-coverage
after_success:
  - npm run semantic-release

